on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo pip install -r src/requirements.txt
          python -m pip install --upgrade pip

      # Use Docker Compose v2 (built-in)
      - name: Build with Docker Compose
        run: docker compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/calculator
            cd /home/ubuntu/calculator
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io docker-compose-plugin
              sudo systemctl enable --now docker
              sudo usermod -aG docker ubuntu
              newgrp docker
            fi
              docker compose pull
              docker compose up -d --build

          
          
